### ISSUE TITLE
[design] Why require a Monad?

### ISSUE THREAD

**Issue by julienrf** [atnos-org/origami#2]
This is the current definition of `Fold`:

~~~ scala
trait Fold[M[_], A, B] { self =>
  implicit def monad: Monad[M]

  type S

  def start: M[S]
  def fold: (S, A) => M[S]
  def end(s: S): M[B]

  /** map the output value */
  def map[C](f: B => C) = new Fold[M, A, C] {
    type S = self.S
    implicit val monad: Monad[M] = self.monad

    def start = self.start
    def fold = self.fold
    def end(s: S) = self.end(s).map(f)
  }

  …
}
~~~

We see that at the beginning there is an `implicit def monad: Monad[M]`. However, we actually *need* a monad to only implement a few operations (`mapFlatten` and some others).

Did you consider a design like the following?

~~~ scala
trait Fold[M[_], A, B] { self =>
  type S

  def start: M[S]
  def fold: (S, A) => M[S]
  def end(s: S): M[B]

  /** map the output value */
  def map[C](f: B => C)(implicit functor: Functor[M]) = new Fold[M, A, C] {
    type S = self.S

    def start = self.start
    def fold = self.fold
    def end(s: S) = self.end(s).map(f)
  }

  …
}
~~~

The idea is to require typeclasses instances _per operation_. In that case it makes it possible to require only a `Functor` (instead of a `Monad`) to implement `map`.

**Comment by julienrf** [comment]
(That being said I have no concrete example where I’m blocked because I can not provide a monad…)

**Comment by etorreborre** [comment]
Yes I also considered this option but eventually I chose the same design as in the `foldl` library in Haskell. Since `FoldM` is likely to be only used with streaming abstractions where a monad is needed I don't think this is going to be an issue.

**Comment by julienrf** [comment]
Thanks for the explanation :)
