### ISSUE TITLE
support for scala 2.13

### ISSUE THREAD

**Issue by trobert** [atnos-org/origami#34]
Would you be willing to release a 2.13 build ?
I gave it a try locally, and apart for the necessary lib updates and dropping scalaz-stream, everything seems to work fine.

Thanks

**Comment by etorreborre** [comment]
I released `6.0.0` for Scala 2.13 (and other versions as well): https://repo1.maven.org/maven2/org/atnos/origami-core_2.13. Thanks for reminding me, I started doing this last week but got blocked on some publishing issues.
