### ISSUE TITLE
add prefilter and friends methods

### ISSUE THREAD

**Issue by trobert** [atnos-org/origami#35]
Hi,

Today we have `contramap` to map on the input element.
What would be your thoughts on adding to `Fold[M,A,B]` some filtering methods on input elements like:
```scala
def contramapFilter[C](f: A => Option[C]): Fold[M, C, B]

def preFilter(f: A => Boolean): Fold[M, A, B]  // contraFilter ?

def preCollect[C](pf: PartialFunction[A, C]): Fold[M, C, B] // contraCollect ?

def flattenOption: Fold[M, Option[A], B] 
```

(names can be discussed)

Note: this is like cats `FunctorFilter` but on the contravariant element.

I would be happy to submit a PR if your feedback is positive.

**Comment by etorreborre** [comment]
Yes please I would be happy to receive a PR for this. You can of course take some inspiration from the `foldl` library which has `prefilter` and adapt those functions to Scala idioms (there's no `PartialFunction` in Haskell for example): https://hackage.haskell.org/package/foldl-1.4.5/docs/Control-Foldl.html#v:prefilter

**Comment by trobert** [comment]
foldl (and cats FunctorFilter) was indeed my source of inspiration for proposing this. So I'll do the PR in the next days, hopefully.

**Comment by trobert** [comment]
done in #36
