### ISSUE TITLE
Consider adding origami to cats ecosystem

### ISSUE THREAD

**Issue by BennyHill** [atnos-org/origami#6]
Same as for eff at https://github.com/typelevel/cats#the-cats-ecosystem.

Esp if https://github.com/atnos-org/origami/issues/5 is done :wink:

**Comment by etorreborre** [comment]
Thanks I'll try to do that this week.

**Comment by etorreborre** [comment]
I created a [PR] (https://github.com/typelevel/cats/pull/1845) for it in typelevel/cats.

One big thing is still missing (even before an `Aggregator` :-)). It is some compiler-checked documentation for the library. @taojang might volunteer to do that with me. Let's me it happen!

**Comment by etorreborre** [comment]
The cats PR is now merged.
